---
- name: Ensure firewalld is deployed
  hosts: "{{ serveur }}"
  become: true

  tasks:
    - name: Ensure firewalld is installed
      yum:
        name: firewalld
        state: present

    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: yes
